#cloud-config
write_files:
  - content: |
      #!/bin/bash

      export VPNHOST=${vpn_host}
      export VPNUSERNAME=${vpn_user_name}
      export EMAILADDR=${email}

      curl -LO "https://raw.githubusercontent.com/mpryahin/aws-ikev2-vpn/main/ikev2-setup.sh"
      curl -LO "https://raw.githubusercontent.com/mpryahin/aws-ikev2-vpn/main/ikev2-setup.sha256"

      if sha256sum --check ikev2-setup.sha256; then
        echo "Checksum verification passed."
      else
        echo "Checksum verification failed."
        exit 1
      fi

      chmod +x ikev2-setup.sh
      ./ikev2-setup.sh
    owner: root:root
    permissions: "754"
    path: /root/init.sh

runcmd:
  - [ bash, /root/init.sh ]
